/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1df08de98ab1fd5fc282714f1a6d83ab)
interface __BaseEnv_Env {
	WAITLIST: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
